CompileSpeed.c: generators/Cgenerator.py
	python3 generators/Cgenerator.py

CompileSpeed.ths: generators/THSgenerator.py
	python3 generators/THSgenerator.py

CompileSpeed.qhs: generators/QHSgenerator.py
	python3 generators/QHSgenerator.py